# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Optionally build your docs in additional formats such as PDF
formats:
   - pdf

# Specify which OS to use when building docs
build:
   os: "ubuntu-22.04"
   tools: 
      python: "3.8"
   jobs:
      post_install:
         - pip install -r docs/requirements.txt

sphinx:
   configuration: docs/source/conf.py

submodules:
   include: all
   recursive: true
